from __future__ import annotations

from typing import Protocol, Any


class LeaseProvider(Protocol):
    def list_candidates(self, requirements: dict[str, Any]) -> list[dict[str, Any]]: ...

    def acquire(self, candidate: dict[str, Any], lease_request: dict[str, Any]) -> dict[str, Any]: ...

    def heartbeat(self, lease_id: str) -> dict[str, Any]: ...

    def release(self, lease_id: str) -> dict[str, Any]: ...

    def describe(self, lease_id: str) -> dict[str, Any]: ...
