[program:ipfs-daemon]
command=/opt/xforce-ai/bin/xforce-ipfs-daemon
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
environment=HOME="/home/user"
stdout_logfile=/tmp/xforce-ai/services/ipfs-daemon/stdout.log
stderr_logfile=/tmp/xforce-ai/services/ipfs-daemon/stderr.log
