from __future__ import annotations

UNVERIFIED = "Unverified"
VERIFICATION_QUEUED = "Verification_Queued"
VERIFICATION_IN_PROGRESS = "Verification_In_Progress"
CERTIFIED_ACTIVE = "Certified_Active"
CERTIFIED_DEGRADED = "Certified_Degraded"
CERTIFICATION_FAILED = "Certification_Failed"
CERTIFICATION_EXPIRED = "Certification_Expired"
LEASE_HELD = "Lease_Held"
LEASE_RELEASED = "Lease_Released"
QUARANTINED = "Quarantined"

ALLOWED_TRANSITIONS = {
    UNVERIFIED: {VERIFICATION_QUEUED, QUARANTINED},
    VERIFICATION_QUEUED: {VERIFICATION_IN_PROGRESS, QUARANTINED},
    VERIFICATION_IN_PROGRESS: {CERTIFIED_ACTIVE, CERTIFIED_DEGRADED, CERTIFICATION_FAILED, QUARANTINED},
    CERTIFIED_ACTIVE: {LEASE_HELD, CERTIFICATION_EXPIRED, QUARANTINED},
    CERTIFIED_DEGRADED: {LEASE_HELD, CERTIFICATION_EXPIRED, VERIFICATION_QUEUED, QUARANTINED},
    CERTIFICATION_FAILED: {VERIFICATION_QUEUED, QUARANTINED},
    CERTIFICATION_EXPIRED: {VERIFICATION_QUEUED, QUARANTINED},
    LEASE_HELD: {LEASE_RELEASED, QUARANTINED},
    LEASE_RELEASED: {CERTIFIED_ACTIVE, CERTIFIED_DEGRADED, QUARANTINED},
    QUARANTINED: {VERIFICATION_QUEUED},
}


def can_transition(source: str, target: str) -> bool:
    return target in ALLOWED_TRANSITIONS.get(source, set())
