[unix_http_server]
file=/tmp/xforce-ai/supervisor/supervisor.sock
chmod=0700

[supervisord]
logfile=/tmp/xforce-ai/supervisor/logs/supervisord.log
pidfile=/tmp/xforce-ai/supervisor/supervisord.pid
childlogdir=/tmp/xforce-ai/supervisor/logs
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/xforce-ai/supervisor/supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf
